id: I4989860C
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:09.956112
last_modified: 2023-02-09 14:52:09.956268
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: sa
bases:
  388C:
    base_file: 388C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
